.TH gnubiff 1 "21 August 2005" "Version 2.1.6" "gnubiff Manual Pages"
.SH NAME
gnubiff \- a mail notification program supporting GTK+ and GNOME
.SH SYNOPSIS
.B gnubiff
.RI [ options ]
.SH DESCRIPTION
gnubiff is a mail notification program that checks for mail, displays
headers when new mail has arrived and allow to read first lines of new
messages. It relies on the GNOME and GTK libraries but can be compiled
and used with or without GNOME support. Supported protocols are pop3,
apop, imap4, mh, qmail and mailfile.  Furthermore, gnubiff is fully
configurable with a lot of options like polltime, poptime, sounds, mail
reader, mailbox names, etc. and can also filter spam. Note that
gnubiff is not a mail reader even if it offers the possibility of
reading very first lines of new messages. If you send some requests for
specific features to be implemented, keep that in mind!
.SH OPTIONS
gnubiff accepts the following command line options:
.TP
.BI "\-c " filename, " \-\-config " filename
Use the specified file as configuration file (default is ~/.gnubiffrc)
.TP
.B \-n, \-\-noconfigure
Skip the configure process
.TP
.B \-?, \-\-help
Show summary of options
.TP
.B  \-v, \-\-version
Print version information
.SH FILES
.TP
.I ~/.gnubiffrc
user specific options file
.SH BUGS
None known.
.SH AUTHORS
gnubiff was developed by Nicolas Rougier
<Nicolas.Rougier@loria.fr>. This manpage was written by Roland Stigge
<stigge@antcom.de> for Debian. It can be used elsewhere, of course.
